name: example_data_pipeline
version: 1.0.0
config-version: 2

profile: example_data_pipeline

model-paths:
  - models
test-paths:
  - tests
macro-paths:
  - macros
target-path: target
clean-targets:
  - target
  - dbt_packages

models:
  example_data_pipeline:
    +schema: gold
    +file_format: iceberg
    staging:
      +materialized: table
    features:
      +schema: silver
      +materialized: table
    marts:
      dimensions:
        +materialized: table
      facts:
        +materialized: table
      marts:
        +materialized: table
    semantic:
      +materialized: table
