catalog.type=rest
uri=http://iceberg-rest.data-platform-infra:8181
warehouse=s3://warehouse/
s3.endpoint=http://minio.data-platform-infra:9000
s3.path-style-access=true
s3.access-key-id=minio
s3.secret-access-key=minio123
