spark.master                          local[*]
spark.ui.enabled                      true
spark.ui.port                         4040
spark.jars                            /app/spark/jars/iceberg-spark-runtime-4.0_2.13-1.10.1.jar,/app/spark/jars/hadoop-aws-3.4.1.jar,/app/spark/jars/aws-java-sdk-bundle-1.12.780.jar,/app/spark/jars/iceberg-aws-bundle-1.10.1.jar
spark.sql.extensions                  org.apache.iceberg.spark.extensions.IcebergSparkSessionExtensions
spark.sql.catalog.iceberg           org.apache.iceberg.spark.SparkCatalog
spark.sql.catalog.iceberg.type      rest
spark.sql.catalog.iceberg.uri       http://iceberg-rest.data-platform-infra:8181
spark.sql.catalog.iceberg.warehouse s3://warehouse/
spark.sql.catalog.iceberg.io-impl   org.apache.iceberg.aws.s3.S3FileIO
spark.sql.catalog.iceberg.s3.endpoint http://minio.data-platform-infra:9000
spark.sql.catalog.iceberg.s3.path-style-access true
spark.hadoop.fs.s3a.endpoint          http://minio.data-platform-infra:9000
spark.hadoop.fs.s3a.access.key        minio
spark.hadoop.fs.s3a.secret.key        minio123
spark.hadoop.fs.s3a.path.style.access true
spark.hadoop.fs.s3a.impl              org.apache.hadoop.fs.s3a.S3AFileSystem
