from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True)
class StackDefinition:
    name: str
    description: str
    services: tuple[str, ...]
    validation_sections: tuple[str, ...]
    validation_services: tuple[str, ...]
    validation_http_endpoints: tuple[str, ...]
    validation_trino_checks: tuple[str, ...] = ()


STACKS: dict[str, StackDefinition] = {
    "ingestion": StackDefinition(
        name="ingestion",
        description="Postgres CDC and event intake into Kafka plus schema management.",
        services=(
            "postgres",
            "kafka",
            "kafka-bootstrap",
            "schema-registry",
            "schema-registry-bootstrap",
            "kafka-connect-source",
            "kafka-connect-source-bootstrap",
        ),
        validation_sections=("services", "http", "connect", "kafka", "postgres", "generator"),
        validation_services=(
            "postgres",
            "kafka",
            "schema-registry",
            "kafka-connect-source",
        ),
        validation_http_endpoints=("schema_registry", "kafka_connect_source"),
    ),
    "stream-processing": StackDefinition(
        name="stream-processing",
        description="Kafka-to-Bronze and online feature processing with sink connectors, Flink, Redis, and Iceberg.",
        services=(
            "postgres",
            "kafka",
            "kafka-bootstrap",
            "schema-registry",
            "schema-registry-bootstrap",
            "kafka-connect-sinks",
            "kafka-connect-sinks-bootstrap",
            "minio",
            "minio-bootstrap",
            "iceberg-rest",
            "iceberg-cdc-bootstrap",
            "redis",
            "flink-python-bootstrap",
            "flink-jars-bootstrap",
            "flink-jobmanager",
            "flink-taskmanager",
            "flink-bootstrap-bronze-events",
            "flink-bootstrap-online-features",
            "trino",
        ),
        validation_sections=("services", "http", "connect", "kafka", "flink", "redis", "generator", "trino"),
        validation_services=(
            "postgres",
            "kafka",
            "schema-registry",
            "kafka-connect-sinks",
            "minio",
            "iceberg-rest",
            "flink-jobmanager",
            "flink-taskmanager",
            "redis",
            "trino",
        ),
        validation_http_endpoints=("schema_registry", "kafka_connect_sinks", "minio", "iceberg_rest", "flink", "trino"),
        validation_trino_checks=(
            "bronze_sales_rep_cdc",
            "bronze_customer_cdc",
            "bronze_advertiser_cdc",
            "bronze_product_cdc",
            "bronze_campaign_cdc",
            "bronze_campaign_product_cdc",
            "bronze_customer_session_cdc",
            "bronze_order_header_cdc",
            "bronze_order_item_cdc",
            "bronze_sales_activity_cdc",
            "bronze_session_event_raw",
        ),
    ),
    "streaming": StackDefinition(
        name="streaming",
        description="Combined ingestion plus stream-processing flow from source systems into Bronze and Redis.",
        services=(
            "postgres",
            "kafka",
            "kafka-bootstrap",
            "schema-registry",
            "schema-registry-bootstrap",
            "kafka-connect-source",
            "kafka-connect-source-bootstrap",
            "kafka-connect-sinks",
            "kafka-connect-sinks-bootstrap",
            "minio",
            "minio-bootstrap",
            "iceberg-rest",
            "iceberg-cdc-bootstrap",
            "redis",
            "flink-python-bootstrap",
            "flink-jars-bootstrap",
            "flink-jobmanager",
            "flink-taskmanager",
            "flink-bootstrap-bronze-events",
            "flink-bootstrap-online-features",
            "trino",
        ),
        validation_sections=("services", "http", "connect", "kafka", "flink", "postgres", "redis", "generator", "trino"),
        validation_services=(
            "postgres",
            "kafka",
            "schema-registry",
            "kafka-connect-source",
            "kafka-connect-sinks",
            "minio",
            "iceberg-rest",
            "flink-jobmanager",
            "flink-taskmanager",
            "redis",
            "trino",
        ),
        validation_http_endpoints=("schema_registry", "kafka_connect_source", "kafka_connect_sinks", "minio", "iceberg_rest", "flink", "trino"),
        validation_trino_checks=(
            "bronze_sales_rep_cdc",
            "bronze_customer_cdc",
            "bronze_advertiser_cdc",
            "bronze_product_cdc",
            "bronze_campaign_cdc",
            "bronze_campaign_product_cdc",
            "bronze_customer_session_cdc",
            "bronze_order_header_cdc",
            "bronze_order_item_cdc",
            "bronze_sales_activity_cdc",
            "bronze_session_event_raw",
        ),
    ),
    "batch": StackDefinition(
        name="batch",
        description="Spark batch processing, dbt Gold modeling, and metadata publishing.",
        services=(
            "postgres",
            "minio",
            "minio-bootstrap",
            "iceberg-rest",
            "spark-jars-bootstrap",
            "spark",
            "spark-bootstrap",
            "dbt",
            "dbt-scheduler",
            "metadata",
            "trino",
        ),
        validation_sections=("services", "http", "metadata", "dbt", "trino"),
        validation_services=("postgres", "minio", "iceberg-rest", "spark", "spark-bootstrap", "dbt", "dbt-scheduler", "metadata", "trino"),
        validation_http_endpoints=("minio", "iceberg_rest", "spark_ui", "metadata", "trino"),
        validation_trino_checks=(
            "silver_customer_current",
            "silver_session_event_clean",
            "silver_order_header",
            "silver_customer_daily_metrics",
            "gold_dim_customer",
            "gold_fct_session_events",
            "gold_fct_orders",
            "gold_mart_customer_conversion",
            "gold_mart_campaign_performance",
            "ml_customer_purchase_features_v1",
            "ml_customer_purchase_realtime_features_v1",
            "ml_campaign_success_features_v1",
            "ml_advertiser_budget_features_v1",
        ),
    ),
    "analytics": StackDefinition(
        name="analytics",
        description="Trino and Superset analytics layer over Iceberg and metadata.",
        services=(
            "postgres",
            "minio",
            "minio-bootstrap",
            "iceberg-rest",
            "trino",
            "superset",
            "superset-bootstrap",
            "metadata",
        ),
        validation_sections=("services", "http", "trino", "metadata"),
        validation_services=("postgres", "minio", "iceberg-rest", "trino", "superset", "metadata"),
        validation_http_endpoints=("minio", "iceberg_rest", "trino", "superset", "metadata"),
        validation_trino_checks=(
            "gold_dim_customer",
            "gold_fct_session_events",
            "gold_fct_orders",
            "gold_mart_customer_conversion",
            "gold_mart_campaign_performance",
        ),
    ),
    "ml": StackDefinition(
        name="ml",
        description="ML training, registry, and demo scoring over Trino, Redis, Iceberg, MinIO, and metadata.",
        services=(
            "postgres",
            "minio",
            "minio-bootstrap",
            "iceberg-rest",
            "trino",
            "redis",
            "ml-training",
            "ml-inference",
            "metadata",
        ),
        validation_sections=("services", "http", "metadata", "ml"),
        validation_services=("postgres", "minio", "iceberg-rest", "trino", "redis", "ml-inference", "metadata"),
        validation_http_endpoints=("minio", "iceberg_rest", "trino", "ml_inference", "metadata"),
    ),
}


DEFAULT_VALIDATION_SECTIONS: tuple[str, ...] = (
    "services",
    "http",
    "connect",
    "kafka",
    "flink",
    "postgres",
    "trino",
    "redis",
    "metadata",
    "dbt",
    "generator",
    "ml",
)


DEFAULT_VALIDATION_SERVICES: tuple[str, ...] = (
    "postgres",
    "kafka",
    "schema-registry",
    "kafka-connect-source",
    "kafka-connect-sinks",
    "minio",
    "iceberg-rest",
    "flink-jobmanager",
    "flink-taskmanager",
    "spark",
    "spark-bootstrap",
    "redis",
    "trino",
    "dbt",
    "metadata",
    "ml-inference",
    "superset",
)


DEFAULT_VALIDATION_HTTP_ENDPOINTS: tuple[str, ...] = (
    "schema_registry",
    "kafka_connect_source",
    "kafka_connect_sinks",
    "minio",
    "iceberg_rest",
    "trino",
    "superset",
    "flink",
    "metadata",
    "ml_inference",
    "spark_ui",
)
